import 'server-only'
import { readFileSync } from 'node:fs'
import path from 'node:path'

/**
 * The archive's own record of who was who.
 *
 * The 8BRCAM extraction resolved thousands of handles down to ~1,950 people, and the thing it
 * resolved them BY was the Yahoo Messenger ID. That is what makes this table able to answer a
 * question the live database cannot: `Trojan__Man__` and `Top__Dawg__` look nothing alike, but both
 * were used by the holder of the YIM `top__dawg__`, so somebody typing the second when the first
 * already exists is about to create a duplicate. No amount of string similarity between those two
 * handles would ever reveal it — only the shared Yahoo ID does.
 *
 * This exposes that graph as a lookup. It is EVIDENCE, not a rule: it says "the archive recorded
 * these as the same person", and the operator decides.
 *
 * ── Loaded once, from the repo ───────────────────────────────────────────────────────────────────
 * The CSVs ship with the source, are a few hundred kilobytes, and never change at runtime, so they
 * are parsed on first use and kept. A database import would be the alternative and is a far larger
 * commitment: it would put a second copy of archive identity into tables that the live merge tools
 * act on, and the two would drift.
 */

export interface ArchiveIdentity {
  playerId: string
  primaryName: string
  /** Every display handle recorded for this person, as spelled in the archive. */
  handles: string[]
  /** Every Yahoo Messenger ID recorded for this person. */
  yims: string[]
  /** Archive player ids folded into this identity because their YIMs matched. */
  mergedFrom: string[]
  firstYear: string | null
  lastYear: string | null
}

/** Case- and punctuation-insensitive, matching how handles are compared everywhere else. */
function key(value: string | null | undefined): string {
  return (value ?? '').toLowerCase().replace(/[^a-z0-9]/g, '')
}

interface Index {
  byKey: Map<string, ArchiveIdentity[]>
  identities: Map<string, ArchiveIdentity>
  loaded: boolean
  rows: number
}

let cache: Index | null = null

/**
 * A minimal CSV reader.
 *
 * These files are generated by the extractor and contain no quoted commas or embedded newlines —
 * checked, not assumed. Pulling in a parser for three columns of machine-written data would be more
 * dependency than the job needs.
 */
function parseCsv(text: string): Record<string, string>[] {
  const lines = text.split(/\r?\n/).filter((l) => l.trim() !== '')
  if (lines.length === 0) return []
  const head = lines[0].replace(/^﻿/, '').split(',')
  return lines.slice(1).map((line) => {
    const cells = line.split(',')
    const row: Record<string, string> = {}
    head.forEach((h, i) => { row[h] = (cells[i] ?? '').trim() })
    return row
  })
}

function load(): Index {
  if (cache) return cache

  const empty: Index = { byKey: new Map(), identities: new Map(), loaded: false, rows: 0 }
  const base = path.join(process.cwd(), 'archive', 'cueverse-prime', 'data', 'csv')

  let players: Record<string, string>[]
  let aliases: Record<string, string>[]
  try {
    players = parseCsv(readFileSync(path.join(base, 'players.csv'), 'utf8'))
    aliases = parseCsv(readFileSync(path.join(base, 'player_aliases.csv'), 'utf8'))
  } catch {
    // The archive is a convenience, not a dependency. If it is not on disk the duplicate panel
    // simply loses one of its signals rather than the page failing to render.
    cache = empty
    return cache
  }

  const identities = new Map<string, ArchiveIdentity>()
  for (const p of players) {
    if (!p.player_id) continue
    identities.set(p.player_id, {
      playerId: p.player_id,
      primaryName: p.primary_name || p.player_id,
      handles: [],
      yims: [],
      mergedFrom: [],
      firstYear: p.first_year || null,
      lastYear: p.last_year || null,
    })
  }

  for (const a of aliases) {
    const id = identities.get(a.player_id)
    if (!id || !a.alias) continue
    if (a.alias_type === 'ym_id') id.yims.push(a.alias)
    else id.handles.push(a.alias)
  }

  /*
   * Fold together archive players whose YIMs differ only by punctuation.
   *
   * The extraction keyed identity on the EXACT YIM string, so `top__dawg__` and `top__dawg___`
   * became two people. They are one Yahoo account typed two ways — the shared-YIM report found 28
   * such pairs — and leaving them separate here would mean the panel misses precisely the
   * duplicates it exists to catch.
   */
  const yimOwner = new Map<string, ArchiveIdentity>()
  for (const id of [...identities.values()].sort((a, b) => a.playerId.localeCompare(b.playerId))) {
    for (const y of id.yims) {
      const k = key(y)
      if (!k) continue
      const first = yimOwner.get(k)
      if (!first) { yimOwner.set(k, id); continue }
      if (first === id) continue
      // Merge the later record into the earlier one, then retire it.
      first.handles.push(...id.handles)
      first.yims.push(...id.yims)
      first.mergedFrom.push(id.playerId)
      if (id.firstYear && (!first.firstYear || id.firstYear < first.firstYear)) first.firstYear = id.firstYear
      if (id.lastYear && (!first.lastYear || id.lastYear > first.lastYear)) first.lastYear = id.lastYear
      identities.delete(id.playerId)
      for (const y2 of id.yims) {
        const k2 = key(y2)
        if (k2 && !yimOwner.has(k2)) yimOwner.set(k2, first)
      }
    }
  }

  // One key per spelling, pointing at everyone who used it. A handle reused by two archive players
  // is rare but real, so the value is a list rather than a single identity.
  const byKey = new Map<string, ArchiveIdentity[]>()
  const add = (raw: string, id: ArchiveIdentity) => {
    const k = key(raw)
    if (!k) return
    const list = byKey.get(k)
    if (list) { if (!list.includes(id)) list.push(id) } else byKey.set(k, [id])
  }
  for (const id of identities.values()) {
    add(id.primaryName, id)
    for (const h of id.handles) add(h, id)
    for (const y of id.yims) add(y, id)
  }

  cache = { byKey, identities, loaded: true, rows: aliases.length }
  return cache
}

/** Whether the archive index is available at all. Used to explain an empty result honestly. */
export function archiveAvailable(): boolean {
  return load().loaded
}

/**
 * Archive people who ever used this handle, name or Yahoo ID.
 *
 * Returns every match, because a handle genuinely reused by two people is information the operator
 * needs rather than an ambiguity to resolve silently.
 */
export function lookupArchiveIdentities(term: string): ArchiveIdentity[] {
  const k = key(term)
  if (k.length < 2) return []
  return load().byKey.get(k) ?? []
}

/**
 * Every OTHER name an archive person went by.
 *
 * This is the part that catches the duplicate no string comparison can: given `trojan_man`, it
 * returns `Top__Dawg__` and the rest, so an existing member under any of those names can be found.
 */
export function otherNamesFor(identity: ArchiveIdentity, excluding: string): string[] {
  const skip = key(excluding)
  const all = [identity.primaryName, ...identity.handles, ...identity.yims]
  const seen = new Set<string>()
  const out: string[] = []
  for (const name of all) {
    const k = key(name)
    if (!k || k === skip || seen.has(k)) continue
    seen.add(k)
    out.push(name)
  }
  return out
}

/**
 * The Yahoo ID that justifies the link, or null when no single one does.
 *
 * Only returned when it can actually be defended: either the typed term IS the Yahoo ID, or the
 * person has exactly one on file so there is no ambiguity about which one connects them. Where
 * several exist, naming an arbitrary one would state a fact that is not established — and these are
 * real people's personal addresses, so an admin panel should print one only when it means something.
 */
export function linkingYim(identity: ArchiveIdentity, term: string): string | null {
  const k = key(term)
  for (const y of identity.yims) if (key(y) === k) return y
  const distinct = [...new Set(identity.yims.map((y) => key(y)))]
  return distinct.length === 1 ? identity.yims[0] : null
}
