// RETIRED — see scripts/_retired.mjs. Importing this file refuses to run.
import '../_retired.mjs'

/**
 * archive:report — render human-readable Markdown reports from the staging data and
 * validation summary. Deterministic (no timestamps). Reads only; writes to reports/archive/.
 */
import { STAGING_DIR, REPORTS_DIR, readJson, writeText } from './lib/io.mjs'

const s = readJson(REPORTS_DIR, 'validation-summary.json')
const queue = readJson(REPORTS_DIR, 'review-queue.json')
const manifest = readJson(STAGING_DIR, 'manifest.json')

const table = (rows) => rows.map((r) => `| ${r[0]} | ${r[1]} |`).join('\n')
const kvTable = (obj) =>
  `| Key | Count |\n|---|---|\n${Object.entries(obj)
    .map(([k, v]) => `| ${k} | ${v} |`)
    .join('\n')}`
const countBy = (type) => queue.filter((r) => r.type === type).length

const NOTE =
  '> Generated by `npm run archive:report` from the read-only 8BRCAM archive. Preview/staging only — nothing has been imported to the database.'

/* ---------------- ARCHIVE_STAGING_SUMMARY ---------------- */
writeText(
  REPORTS_DIR,
  'ARCHIVE_STAGING_SUMMARY.md',
  `# Archive Staging Summary

${NOTE}

## Source files read (${manifest.sourceFiles.length})

| File | Rows |
|---|---|
${manifest.sourceFiles.map((f) => `| ${f.file} | ${f.rows} |`).join('\n')}

## Staging entity counts

${kvTable(s.counts)}

## Import readiness (headline)

- Schema blockers: **${s.importReadiness.schemaBlockers.length}**
- High-severity issues: **${s.importReadiness.highSeverityIssues}**
- Items requiring review: **${s.importReadiness.itemsRequiringReview}**
- Ready for a reviewed import: **${s.importReadiness.readyForReviewedImport ? 'yes' : 'no'}**

See the domain reports: IDENTITY_RESOLUTION_REPORT · COMPETITION_VALIDATION_REPORT ·
MATCH_VALIDATION_REPORT · CHAMPIONSHIP_VALIDATION_REPORT · IMPORT_READINESS_REPORT.
`,
)

/* ---------------- IDENTITY_RESOLUTION_REPORT ---------------- */
const id = s.identity
writeText(
  REPORTS_DIR,
  'IDENTITY_RESOLUTION_REPORT.md',
  `# Identity Resolution Report

${NOTE}

Canonical archive identities are preserved (stable \`P####\` ids). Existing merges and
splits are preserved. **Uncertain identities are never auto-merged** — they go to the
review queue.

| Metric | Count |
|---|---|
| Confirmed canonical identities | ${id.confirmedCanonical} |
| Exact alias matches (alias = canonical name) | ${id.exactAliasMatches} |
| Normalized alias matches | ${id.normalizedAliasMatches} |
| Existing merges (preserved) | ${id.existingMerges} |
| Existing splits (preserved) | ${id.existingSplits} |
| Shared aliases (one alias → multiple players) | ${id.sharedAliases} |
| Merge candidates (shared YM/email, not merged) | ${id.mergeCandidates} |
| Name-only duplicate groups (LOW — do not merge alone) | ${id.nameOnlyDuplicateGroups} |
| Unresolved aliases (orphans) | ${id.unresolvedAliases} |
| Unresolved players (no name) | ${id.unresolvedPlayers} |

**Review queue:** ${countBy('shared-alias')} shared-alias, ${countBy('merge-candidate')} merge-candidate,
${countBy('name-duplicate')} name-duplicate, ${countBy('unresolved-alias') + countBy('unresolved-player')} unresolved
(see review-queue.json).

Shared aliases are the archive's genuine identity ambiguities (e.g. a messenger id used
by more than one person). They require a human merge/split decision and must not be
auto-resolved.
`,
)

/* ---------------- COMPETITION_VALIDATION_REPORT ---------------- */
const c = s.competitions
writeText(
  REPORTS_DIR,
  'COMPETITION_VALIDATION_REPORT.md',
  `# Competition Validation Report

${NOTE}

Historical archive competitions keep their original identities and are **never labelled
as EGO seasons**. EGO Season 1 remains a separate modern entry linked to the legacy
8B Retro Season 1 identity only by metadata/annotation.

| Metric | Count |
|---|---|
| Competitions (seasons) | ${c.competitions} |
| Divisions | ${c.divisions} |
| Competition issues | ${c.issues} |
| Divisions mislabelled as EGO seasons (must be 0) | ${c.labeledAsEgoSeason} |

### Completeness

${kvTable(c.byCompleteness)}

### Confidence

${kvTable(c.byConfidence)}

Divisions marked \`missing\`/\`partial\` are preserved as-is with honest completeness; no
values are invented. Format is recorded from the archived playoff record where present.
`,
)

/* ---------------- MATCH_VALIDATION_REPORT ---------------- */
const m = s.matches
writeText(
  REPORTS_DIR,
  'MATCH_VALIDATION_REPORT.md',
  `# Match Validation Report

${NOTE}

Missing playoff scores and progression are **preserved as unknown, never invented**.

| Metric | Count |
|---|---|
| Total matches | ${m.total} |
| Group matches | ${m.groupMatches} |
| Playoff matches | ${m.playoffMatches} |
| With score | ${m.withScore} |
| Missing score | ${m.missingScore} |
| Byes | ${m.byes} |
| Missing competitor (non-bye) | ${m.missingCompetitor} |
| Unresolved competitor (unknown id) | ${m.unresolvedCompetitor} |
| Impossible scores (winner ≠ higher score, negatives) | ${m.impossibleScore} |
| Duplicate pairings within a stage | ${m.duplicates} |
| Winner recorded but scores equal (forfeit/admin unclear) | ${m.adminOrForfeitUnclear} |
| Seeds with duplicate numbers | ${m.seedDuplicateNumbers} |
| Seeds with no resolved competitor (handle only) | ${m.seedNullCompetitor} |

### Resolution breakdown

${kvTable(m.byResolution)}

**Impossible scores** and **missing/duplicate** issues are flagged for review, not
corrected. Playoff match results were not recorded in the archive — those matches are
staged with null scores and \`pending\` resolution.
`,
)

/* ---------------- CHAMPIONSHIP_VALIDATION_REPORT ---------------- */
const ch = s.championships
writeText(
  REPORTS_DIR,
  'CHAMPIONSHIP_VALIDATION_REPORT.md',
  `# Championship Validation Report

${NOTE}

Champions are preserved with their archived confidence. **Heuristic champions are never
promoted to verified.** Where a deciding playoff match did not survive, it is recorded
as such — no bracket is reconstructed to fabricate one.

| Metric | Count |
|---|---|
| Championships | ${ch.total} |
| Reconstructed brackets | ${ch.reconstructedBrackets} |
| Deciding match survives | ${ch.decidingMatchSurvives} |
| Attribution conflicts | ${ch.conflicts} |
| Requiring review (non-explicit) | ${ch.requiresReview} |

### Confidence breakdown

${kvTable(ch.byConfidence)}

Only **explicit** champions are import-safe without review. Heuristic / reconstructed /
unknown champions require a human decision before verification.
`,
)

/* ---------------- IMPORT_READINESS_REPORT ---------------- */
const ir = s.importReadiness
writeText(
  REPORTS_DIR,
  'IMPORT_READINESS_REPORT.md',
  `# Import Readiness Report

${NOTE}

**No records are imported in this phase.** \`archive:import\` is dry-run only.

| Metric | Value |
|---|---|
| Genuine schema blockers | ${ir.schemaBlockers.length} |
| High-severity issues | ${ir.highSeverityIssues} |
| Items requiring review | ${ir.itemsRequiringReview} |
| Ready for a reviewed import | ${ir.readyForReviewedImport ? 'yes' : 'no'} |

## Review queue by type

${kvTable(
  queue.reduce((acc, r) => {
    acc[r.type] = (acc[r.type] || 0) + 1
    return acc
  }, {}),
)}

## Manual decisions required before real import

1. Resolve **shared aliases** (${countBy('shared-alias')}) — merge or split each ambiguous identity.
2. Review **merge candidates** (${countBy('merge-candidate')}) and **name-only duplicates** (${countBy('name-duplicate')}) — do not merge on name alone.
3. Decide handling of **non-explicit championships** (${ch.requiresReview}) — keep as heuristic/unknown or verify.
4. Review **impossible/forfeit-unclear matches** (${m.impossibleScore + m.adminOrForfeitUnclear}).
5. Confirm the **EGO Season 1 seeding annotation** stays an administrative note (not a results correction).
6. Choose an **entry method** default for archive \`CompetitionEntry\` rows (currently null/unknown).

## Blockers

${ir.schemaBlockers.length === 0 ? 'None. The existing Prisma schema can represent the staged entities.' : ir.schemaBlockers.map((b) => `- ${b}`).join('\n')}
`,
)

console.log('archive:report complete →', REPORTS_DIR)
console.log('  ARCHIVE_STAGING_SUMMARY.md, IDENTITY_RESOLUTION_REPORT.md, COMPETITION_VALIDATION_REPORT.md,')
console.log('  MATCH_VALIDATION_REPORT.md, CHAMPIONSHIP_VALIDATION_REPORT.md, IMPORT_READINESS_REPORT.md')
