-- Double round robin: how many times a pair meets, and which meeting a match is.
--
-- Generated by `prisma migrate diff` from the difference between the deployed schema and
-- schema.prisma, not written by hand -- the column types, defaults and enum values are Prisma's own.
--
-- Both columns carry defaults, so every existing row is already correct without being touched:
-- almost every Season is a single round robin, and every existing match is the first meeting of its
-- pair. Adding them changes no data.
--
-- These objects were applied to the working database directly during the Season 16426 rebuild and
-- never captured as a migration. This is that capture, so the production deployment can stop
-- reconciling the schema with `db push --accept-data-loss` and apply a reviewed migration instead.

-- CreateEnum
CREATE TYPE "SeasonGroupFormat" AS ENUM ('SINGLE_ROUND_ROBIN', 'DOUBLE_ROUND_ROBIN');

-- AlterTable
ALTER TABLE "season" ADD COLUMN     "groupFormat" "SeasonGroupFormat" NOT NULL DEFAULT 'SINGLE_ROUND_ROBIN';

-- AlterTable
ALTER TABLE "season_match" ADD COLUMN     "meeting" INTEGER NOT NULL DEFAULT 1;
