/**
 * Hand-verified playoff brackets for pre-2012 seasons, where the archive stored only
 * pairings (no scores/winners). Sourced from the original 8brcam pages via the
 * Wayback Machine and generated by scripts/parse-wayback-brackets.py (player names
 * resolved from the archive's seeds; champions cross-checked against the archive).
 * Keyed "seasonId:division"; applied over the generated data in archive.ts.
 * Regenerate: `python scripts/parse-wayback-brackets.py --write`.
 */
import raw from './verified-playoffs.json'
import type { SeasonRound } from '@/lib/seasons/archive'

export interface VerifiedPlayoff {
  champion: { name: string; handle?: string }
  runnerUp: { name: string; handle?: string }
  championConfidence: string
  playoff: { rounds: SeasonRound[] }
}

export const VERIFIED_PLAYOFFS = raw as unknown as Record<string, VerifiedPlayoff>
